name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  download-dll:
    runs-on: ubuntu-latest
    steps:
    - name: Download SynthPointer.dll
      run: wget https://github.com/Sett17/SynthPointer.dll/releases/latest/download/SynthPointer.dll
    - name: Upload DLL as artifact
      uses: actions/upload-artifact@v3
      with:
        name: SynthPointer.dll
        path: SynthPointer.dll

  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'
    - name: Decode signing key
      run: echo "${{ secrets.KEYSTORE }}" | base64 -d > app-signing.jks
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Build and Sign APK
      run: |
        cd Android
        ./gradlew assembleRelease -Pandroid.injected.signing.store.file=../app-signing.jks -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: PenFerry-Release.apk
        path: Android/app/build/outputs/apk/release/app-release.apk

  build-go:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.20'
    - name: Build Go app
      run: cd Windows && go build ./cmd/penferry
    - name: Upload Go EXE as artifact
      uses: actions/upload-artifact@v3
      with:
        name: penferry.exe
        path: Windows/penferry.exe

  create-installer:
    needs: [build-go, download-dll]
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Download Go EXE artifact
      uses: actions/download-artifact@v3
      with:
        name: penferry.exe
        path: Windows/
    - name: Download DLL artifact
      uses: actions/download-artifact@v3
      with:
        name: SynthPointer.dll
        path: Windows/
    - name: Install Inno Setup
      run: choco install innosetup
    - name: Create Installer using Inno Setup
      run: |
        "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "Windows\installer.iss"
    - name: Upload Installer as artifact
      uses: actions/upload-artifact@v3
      with:
        name: PenFerryInstaller.exe
        path: Windows\Output\PenFerryInstaller.exe

  create-release:
    needs: [create-installer, build-android]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download APK artifact
        uses: actions/download-artifact@v3
        with:
          name: PenFerry-Release.apk

      - name: Download Go EXE artifact
        uses: actions/download-artifact@v3
        with:
          name: penferry.exe

      - name: Download DLL artifact
        uses: actions/download-artifact@v3
        with:
          name: SynthPointer.dll

      - name: Download Installer artifact
        uses: actions/download-artifact@v3
        with:
          name: PenFerryInstaller.exe

      - name: Zip EXE and DLL
        run: |
          zip PenFerry-Windows.zip penferry.exe SynthPointer.dll

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            PenFerry-Release.apk
            PenFerry-Windows.zip
            PenFerryInstaller.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
